import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/inspector-export")({
  component: InspectorExportPage,
});

const PRIMARY: [number, number, number] = [255, 79, 0];
const DARK: [number, number, number] = [32, 21, 21];
const LIGHT_BG: [number, number, number] = [248, 247, 244];

function InspectorExportPage() {
  const { user } = useAuth();
  const [classId, setClassId] = useState("");
  const [schoolName, setSchoolName] = useState("");
  const [generating, setGenerating] = useState(false);

  const { data: classes } = useQuery({
    queryKey: ["school-classes"],
    queryFn: async () => {
      const { data } = await supabase.from("classes").select("id,name,subject,academic_year").order("name");
      return (data ?? []) as { id: string; name: string; subject: string; academic_year: string }[];
    },
  });

  const cls = classes?.find((c) => c.id === classId);

  async function generate() {
    if (!cls) return;
    setGenerating(true);
    try {
      const [schemeRes, diaryRes, attendanceRes, studentsRes] = await Promise.all([
        supabase.from("scheme_of_work").select("*").eq("class_id", classId).order("week_number"),
        supabase.from("class_diary").select("*").eq("class_id", classId).order("date", { ascending: false }).limit(30),
        supabase.from("class_attendance").select("student_id,status,date").eq("class_id", classId),
        supabase.from("class_students").select("students(id,name)").eq("class_id", classId),
      ]);

      const scheme = (schemeRes.data ?? []) as { week_number: number; topic: string; chapter: string | null; target_date: string | null; status: string }[];
      const diary = (diaryRes.data ?? []) as { date: string; topic_taught: string | null; homework: string | null; periods_taken: number; notes: string | null }[];
      const attendance = (attendanceRes.data ?? []) as { student_id: string; status: string; date: string }[];
      const students = (studentsRes.data ?? []).map((r: { students: { id: string; name: string } | null }) => r.students).filter(Boolean) as { id: string; name: string }[];

      const doc = new jsPDF();
      const teacherEmail = user?.email ?? "Teacher";
      const today = new Date().toLocaleDateString("en-PK", { day: "numeric", month: "long", year: "numeric" });

      // ── Cover page ──
      doc.setFillColor(...PRIMARY);
      doc.rect(0, 0, 210, 48, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("Inspector Report Pack", 14, 20);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(`${cls.name} · ${cls.subject} · ${cls.academic_year}`, 14, 32);
      doc.text(`Prepared: ${today}`, 14, 41);

      doc.setTextColor(...DARK);
      doc.setFillColor(...LIGHT_BG);
      doc.rect(14, 56, 182, 60, "F");
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Document Details", 20, 68);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const details = [
        ["School", schoolName || "(not specified)"],
        ["Class / Section", cls.name],
        ["Subject", cls.subject],
        ["Academic Year", cls.academic_year],
        ["Teacher", teacherEmail],
      ];
      details.forEach(([label, value], i) => {
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 20, 80 + i * 7);
        doc.setFont("helvetica", "normal");
        doc.text(value, 75, 80 + i * 7);
      });

      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text("Contents: Scheme of Work · Teacher Diary · Attendance Register", 14, 130);
      doc.text(`Generated by TutorDash · ${today}`, 105, 287, { align: "center" });

      // ── Scheme of Work ──
      doc.addPage();
      doc.setFillColor(...PRIMARY);
      doc.rect(0, 0, 210, 18, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text("Scheme of Work", 14, 12);

      const completed = scheme.filter((r) => r.status === "completed").length;
      const pct = scheme.length ? Math.round((completed / scheme.length) * 100) : 0;
      doc.setTextColor(...DARK);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(`Progress: ${completed}/${scheme.length} weeks completed (${pct}%)`, 14, 26);

      autoTable(doc, {
        startY: 30,
        head: [["Week", "Topic", "Chapter", "Target Date", "Status"]],
        body: scheme.length
          ? scheme.map((r) => [
              String(r.week_number),
              r.topic,
              r.chapter ?? "—",
              r.target_date ? new Date(r.target_date + "T00:00:00").toLocaleDateString("en-PK", { day: "numeric", month: "short" }) : "—",
              r.status.charAt(0).toUpperCase() + r.status.slice(1),
            ])
          : [["—", "No scheme of work added yet", "—", "—", "—"]],
        headStyles: { fillColor: DARK, textColor: 255, fontSize: 9, fontStyle: "bold" },
        bodyStyles: { fontSize: 8.5, cellPadding: 3 },
        columnStyles: { 0: { cellWidth: 14 }, 1: { cellWidth: 70 }, 2: { cellWidth: 40 }, 3: { cellWidth: 30 }, 4: { cellWidth: 24 } },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 4) {
            const val = String(data.cell.raw);
            if (val === "Completed") data.cell.styles.textColor = [22, 163, 74];
            else if (val === "Skipped") data.cell.styles.textColor = [180, 100, 0];
          }
        },
        alternateRowStyles: { fillColor: LIGHT_BG },
      });

      doc.setFontSize(7);
      doc.setTextColor(160, 160, 160);
      doc.text(`Generated by TutorDash · ${today}`, 105, 287, { align: "center" });

      // ── Teacher Diary ──
      doc.addPage();
      doc.setFillColor(...PRIMARY);
      doc.rect(0, 0, 210, 18, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text("Teacher Diary", 14, 12);

      autoTable(doc, {
        startY: 24,
        head: [["Date", "Topic Taught", "Homework", "Periods", "Notes"]],
        body: diary.length
          ? diary.map((d) => [
              new Date(d.date + "T00:00:00").toLocaleDateString("en-PK", { day: "numeric", month: "short", year: "numeric" }),
              d.topic_taught ?? "—",
              d.homework ?? "—",
              String(d.periods_taken),
              d.notes ?? "—",
            ])
          : [["—", "No diary entries yet", "—", "—", "—"]],
        headStyles: { fillColor: DARK, textColor: 255, fontSize: 9, fontStyle: "bold" },
        bodyStyles: { fontSize: 8, cellPadding: 2.5 },
        columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 60 }, 2: { cellWidth: 50 }, 3: { cellWidth: 16 }, 4: { cellWidth: 36 } },
        alternateRowStyles: { fillColor: LIGHT_BG },
      });

      doc.setFontSize(7);
      doc.setTextColor(160, 160, 160);
      doc.text(`Generated by TutorDash · ${today}`, 105, 287, { align: "center" });

      // ── Attendance Register ──
      doc.addPage();
      doc.setFillColor(...PRIMARY);
      doc.rect(0, 0, 210, 18, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text("Attendance Register", 14, 12);

      const attByStudent: Record<string, { present: number; absent: number; late: number }> = {};
      for (const s of students) {
        attByStudent[s.id] = { present: 0, absent: 0, late: 0 };
      }
      for (const a of attendance) {
        if (attByStudent[a.student_id]) {
          attByStudent[a.student_id][a.status as "present" | "absent" | "late"]++;
        }
      }

      autoTable(doc, {
        startY: 24,
        head: [["#", "Student Name", "Present", "Absent", "Late", "Total Marked", "Attendance %"]],
        body: students.length
          ? students.map((s, i) => {
              const r = attByStudent[s.id] ?? { present: 0, absent: 0, late: 0 };
              const total = r.present + r.absent + r.late;
              const pctAtt = total > 0 ? Math.round(((r.present + r.late) / total) * 100) : 0;
              return [String(i + 1), s.name, String(r.present), String(r.absent), String(r.late), String(total), `${pctAtt}%`];
            })
          : [["—", "No students enrolled", "—", "—", "—", "—", "—"]],
        headStyles: { fillColor: DARK, textColor: 255, fontSize: 9, fontStyle: "bold" },
        bodyStyles: { fontSize: 9, cellPadding: 3 },
        columnStyles: { 0: { cellWidth: 10 } },
        alternateRowStyles: { fillColor: LIGHT_BG },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 6) {
            const val = parseInt(String(data.cell.raw));
            if (!isNaN(val)) {
              if (val >= 75) data.cell.styles.textColor = [22, 163, 74];
              else if (val >= 50) data.cell.styles.textColor = [180, 100, 0];
              else data.cell.styles.textColor = [220, 38, 38];
            }
          }
        },
      });

      // Signature lines
      const sigY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
      if (sigY < 260) {
        doc.setDrawColor(180, 180, 180);
        doc.line(14, sigY, 85, sigY);
        doc.setFontSize(8);
        doc.setTextColor(130, 130, 130);
        doc.setFont("helvetica", "normal");
        doc.text("Teacher Signature", 14, sigY + 5);
        doc.line(125, sigY, 196, sigY);
        doc.text("Principal Signature", 125, sigY + 5);
      }

      doc.setFontSize(7);
      doc.setTextColor(160, 160, 160);
      doc.text(`Generated by TutorDash · ${today}`, 105, 287, { align: "center" });

      doc.save(`Inspector-Pack-${cls.name}-${cls.subject}.pdf`);
      toast.success("Inspector pack downloaded — 4 pages");
    } catch (e) {
      toast.error("Failed to generate PDF");
      console.error(e);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <AppShell>
      <PageHeader
        title="Inspector Export"
        description="One-click PDF pack with Scheme of Work, Diary, and Attendance — ready for inspection."
        actions={
          classId ? (
            <Button onClick={generate} disabled={generating || !cls}>
              <Download className="h-4 w-4 mr-1" />
              {generating ? "Generating…" : "Download Inspector Pack"}
            </Button>
          ) : undefined
        }
      />

      <Card className="mb-6 max-w-lg">
        <CardContent className="pt-6 space-y-4">
          <div>
            <Label>Class *</Label>
            <Select value={classId} onValueChange={setClassId}>
              <SelectTrigger><SelectValue placeholder="Select a class" /></SelectTrigger>
              <SelectContent>
                {classes?.map((c) => (
                  <SelectItem key={c.id} value={c.id}>{c.name} · {c.subject}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label>School name (optional)</Label>
            <Input
              value={schoolName}
              onChange={(e) => setSchoolName(e.target.value)}
              placeholder="e.g. Government High School Lahore"
            />
          </div>
        </CardContent>
      </Card>

      {!classId && (
        <div className="text-center py-20 text-muted-foreground">
          <FileText className="h-10 w-10 mx-auto mb-3 opacity-30" />
          <p className="text-sm">Select a class to generate the inspector pack.</p>
        </div>
      )}

      {classId && cls && (
        <div className="grid gap-4 sm:grid-cols-3">
          {[
            { title: "Scheme of Work", desc: "Full year plan with completion status" },
            { title: "Teacher Diary", desc: "Last 30 lesson entries" },
            { title: "Attendance Register", desc: "Per-student attendance summary" },
          ].map((doc) => (
            <Card key={doc.title}>
              <CardContent className="pt-5 pb-4">
                <div className="flex items-center gap-2 mb-1">
                  <FileText className="h-4 w-4 text-primary" />
                  <span className="text-sm font-semibold">{doc.title}</span>
                </div>
                <p className="text-xs text-muted-foreground">{doc.desc}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </AppShell>
  );
}
